CREATE TABLE skills (
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255));

CREATE TABLE specialties (
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255));

CREATE TABLE developers (
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
firstname VARCHAR(255),
lastname VARCHAR(255),
specialty_id INT,
FOREIGN KEY(specialty_id) REFERENCES specialties(id)
);

CREATE TABLE developers_skills(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
developers_id INT NOT NULL,
skills_id INT NOT NULL,
FOREIGN KEY (developers_id) REFERENCES developers (id),
FOREIGN KEY (skills_id) REFERENCES skills (id));